### ISSUE TITLE
Add Market Type

### ISSUE THREAD

**Issue by tammycamp** [Falicon/AngelList#3]
Is there any way you can add Market type to this API?

 "markets": [
    {
      "id": 448,
      "tag_type": "MarketTag",
      "name": "startups",
      "display_name": "Startups",
      "angellist_url": "http://angel.co/startups-1"
    },

**Comment by Falicon** [comment]
It should return all the fields that are supplied by the api (
https://angel.co/api/spec/startups ) - but let me know if it doesn't or if
you are having trouble.

Thanks!

- Kevin

**Comment by tammycamp** [comment]
Awesome. Thanks.
